### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by DataWorm** [robweber/octoprint-java-lib#6]
I also have two further additions in mind that might follow within the next month. Of course I would provide them to be merged when finished. As the initiator of this project I would like to hear what design you prefer for these two features:

- On one side I need the webcam information from the settings page so I could either define a new pojo structure for these settings or I could directly create a more generic approach: A Map of Strings containing every settings value as a string. Then you could access every current and future setting by `SettingsCommand.getMap().get("server.diskspace.warning")`. I'd prefer the generic solution, that way you can get all settings and not just those we mapped. Also all settings can be received at once (no need to call the api twice and always just parse one section).
- I think some more exception handling might be nice. At least I would like to get some feedback if api key is invalid and it might also be nice to get an exception if connection to api failed for some reasons. If so, would you prefer checked or unchecked exceptions? RuntimeExceptions might not be the best design but on the other side adding checked exceptions to every method of the command clases is also not that pretty. 

P.S. Github does not offer a private messaging system, does it?

**Comment by robweber** [comment]
No, I believe it had a PM system a while ago but has since killed it. 

Thinking about the SettingsCommand class I see what you're thinking. Originally I only had need of the TempProfiles but since that API call returns all the settings it would be nice to go through them in a more generic way. Right now you can do getAllSettings() and return a JSONObject of them all. This is similar to the Map idea, that's the underlying structure anyway. Some of the settings return other objects instead of just strings so a java map structure would need to be like a Map<String,Object>. An example of the full results is in the [settings.json](https://github.com/robweber/octoprint-java-lib/blob/master/src/test/resources/settings.json) test file. 

I agree some better error handling would be nice. The REST API returns HTTP status codes. Right now the HTTP class just fails out if the expected results aren't returned. Although it would change things a bit I think a good approach could be to change the [executeQuery()](https://github.com/robweber/octoprint-java-lib/blob/master/src/main/java/org/octoprint/api/OctoPrintInstance.java#L85) and [executeUpdate()](https://github.com/robweber/octoprint-java-lib/blob/master/src/main/java/org/octoprint/api/OctoPrintInstance.java#L101) methods to return an object (OctoPrintHttpResponse? or similar) that contains the returned result (JSONObject) plus the http status code. Each Command class could then decide to either a) throw an exception or b) handle the error. For some commands just handling the error and returning a boolean or null value may be appropriate. For others, like the API key being invalid, it may make sense to actually throw an exception back to the caller.  For the API error (401 in docs) the executeQuery() and executeUpdate() methods could actually throw this directly since it's kind of a show-stopper. Adding some kind of logging mechanism like sl4j or similar might also help here. That way the error could be logged but not necessarily throw an exception at runtime. 

If you want to work on any of this that sounds great to me. I was looking through the docs and was thinking of adding some more command classes for some of the API endpoints that don't exist yet, like the System endpoint.

**Comment by DataWorm** [comment]
Sorry, haven't found the time to care about the exceotion handling and now I am away for 4 weeks and therefore unable to work on it. I hope I can get back on it in 1-2 months!

**Comment by robweber** [comment]
Sounds good, thanks for letting me know. Appreciate all your additions so far.
